### ISSUE TITLE
Provide checksums (hashes) along with releases

### ISSUE THREAD

**Issue by jzaefferer** [sloppyio/cli#18]
Helps with verifying that the right binary is in place. Not sure what the right format and algorithm is. I guess MD5 is fine for checksums, but maybe not.

**Comment by sevenval-admins** [comment]
I think sha1 or md5 are popular formats.

**Comment by philippfranke** [comment]
I'd like the idea to provide a checksum to verify the data integrity of the released binaries. Nevertheless, it's also important to have reproducible binaries; take a look at [REPRODUCING GO BINARIES BYTE-BY-BYTE](https://blog.filippo.io/reproducing-go-binaries-byte-by-byte/). 

As far as I know, this repository does not allow reproducible builds because the repo does not include the dependencies.

**Comment by jzaefferer** [comment]
> As far as I know, this repository does not allow reproducible builds because the repo does not include the dependencies.

That's fixed now. Not sure if it makes any difference for checksums though.

Since no one ever showed any interest for this, I'll close this for now.
