### ISSUE TITLE
YAML values are falsely interpreted

### ISSUE THREAD

**Issue by bemeyert** [sloppyio/cli#31]
Version: 1.9.1

The YAML file contains a key-value pair like (which, BTW, is correct YAML)
```yaml
[...]
        - HAPROXY_0_AUTH: "Authentication:admin:$1$tNbul7$wVQeY.q1w2/II0C1"
[...]
```
When I run the `sloppy-cli` command I get the error:
```
e2e-tests $ sloppy change sloppy/sloppy.yml
error: missing variable 'wVQeY'.
```
So it seems that the value gets somehow interpreted as a variable. This shouldn't happen.

**Comment by jzaefferer** [comment]
Escaping those dollar symbols with a double backslash should work. Can you give that a try?

See also https://kb.sloppy.io/features/protect-your-app-with-basic-authentication under the CLI header.

**Comment by bemeyert** [comment]
@jzaefferer We already escaped the dollar symbols to fix this. But this is an unexpected behavior, since it kind of violates the YAML standard.

**Comment by jzaefferer** [comment]
I understand that the behaviour is unexpected. Unfortunately the variable replacement feature had been in place long before we ever tried to put dollar signs into regular env vars. Since the workaround is simple enough, we currently don't see a reason to change that feature.

I'm curious what part of the YAML standard this violates.

**Comment by bemeyert** [comment]
Well, looks like I was a bit overzealous ;) It behaves a bit like `docker-compose.yaml`. So it has it's own merits. Clsoing... Cheers
